version: '3.4'
services:
  frontend:
    image: node:alpine
    container_name: project_frontend
    entrypoint: /bin/sh
    restart: always
    ports:
      - 8001:8001
    environment:
      VIRTUAL_HOST: quisvar.com, www.quisvar.com
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    tty: true
    command: 'npm run dev'

networks:
  default:
    external:
      name: proxynet
