version: '3.4'
services:
  frontend:
    image: node:alpine
    container_name: project_frontend
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: quisvar.com, www.quisvar.com
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    tty: true

networks:
  default:
    external:
      name: proxynet
