export const JOB_DATA = [
  { value: 'Ingeniería Agronómica' },
  { value: 'Ingeniería Agroindustrial' },
  { value: 'Ingeniería Topográfica y Agrimensura' },
  { value: 'Ingeniería Civil' },
  { value: 'Arquitectura y Urbanismo' },
  { value: 'Ingeniería Económica' },
  { value: 'Ingeniería Estadística e Informática' },
  { value: 'Ingeniería Geológica' },
  { value: 'Ingeniería Metalúrgica' },
  { value: 'Ingeniería Electrónica' },
  { value: 'Ingeniería Mecánica Eléctrica' },
  { value: 'Ingeniería de Sistemas' },
  { value: 'Ingenieria de Minas' },
  { value: 'Ingeniería Química' },
  { value: 'Ingeniería Sanitaria y Ambiental' },
  { value: 'Ciencias Biológicas' },
  { value: 'Ciencias Biológicas: Pesquería' },
  { value: 'Ciencias Biológicas: Microbiología' },
  { value: 'Nutrición Humana' },
  { value: 'Odontología' },
  { value: 'Enfermería' },
  { value: 'Medicina Humana' },
  { value: 'Medicina Veterinaria y Zootecnia' },
  { value: 'Ciencias Contables' },
  { value: 'Administración' },
  { value: 'Física' },
  { value: 'Inicial' },
  { value: 'Primaria' },
  { value: 'Secundaria' },
  { value: 'Derecho' },
  { value: 'Antropología' },
  { value: 'Arte' },
  { value: 'Ciencias de la Comunicación Social' },
  { value: 'Sociología' },
  { value: 'Turismo' },
  { value: 'Trabajo Social' },
];
