export const JOB_DATA = [
  { value: 'Ingeniería Agronómica', abrv: 'ING' },
  { value: 'Ingeniería Agroindustrial', abrv: 'ING' },
  { value: 'Ingeniería Topográfica y Agrimensura', abrv: 'ING' },
  { value: 'Ingeniería Civil', abrv: 'ING' },
  { value: 'Arquitectura y Urbanismo', abrv: 'ARQ' },
  { value: 'Ingeniería Económica', abrv: 'ING' },
  { value: 'Ingeniería Estadística e Informática', abrv: 'ING' },
  { value: 'Ingeniería Geológica', abrv: 'ING' },
  { value: 'Ingeniería Metalúrgica', abrv: 'ING' },
  { value: 'Ingeniería Electrónica', abrv: 'ING' },
  { value: 'Ingeniería Mecánica Eléctrica', abrv: 'ING' },
  { value: 'Ingeniería de Sistemas', abrv: 'ING' },
  { value: 'Ingenieria de Minas', abrv: 'ING' },
  { value: 'Ingeniería Química', abrv: 'ING' },
  { value: 'Ingeniería Sanitaria y Ambiental', abrv: 'ING' },
  { value: 'Ciencias Biológicas', abrv: 'LIC' },
  { value: 'Ciencias Biológicas: Pesquería', abrv: 'LIC' },
  { value: 'Ciencias Biológicas: Microbiología', abrv: 'LIC' },
  { value: 'Nutrición Humana', abrv: 'LIC' },
  { value: 'Odontología', abrv: 'LIC' },
  { value: 'Enfermería', abrv: 'LIC' },
  { value: 'Medicina Humana', abrv: 'LIC' },
  { value: 'Medicina Veterinaria y Zootecnia', abrv: 'LIC' },
  { value: 'Ciencias Contables', abrv: 'LIC' },
  { value: 'Administración', abrv: 'LIC' },
  { value: 'Gestión Pública y Desarrollo Social', abrv: 'LIC' },
  { value: 'Física', abrv: 'LIC' },
  { value: 'Inicial', abrv: 'LIC' },
  { value: 'Primaria', abrv: 'LIC' },
  { value: 'Secundaria', abrv: 'LIC' },
  { value: 'Derecho', abrv: 'LIC' },
  { value: 'Antropología', abrv: 'LIC' },
  { value: 'Arte', abrv: 'LIC' },
  { value: 'Ciencias de la Comunicación Social', abrv: 'LIC' },
  { value: 'Sociología', abrv: 'LIC' },
  { value: 'Turismo', abrv: 'LIC' },
  { value: 'Trabajo Social', abrv: 'LIC' },
];
